### ISSUE TITLE
Basic nl.net.newff error

### ISSUE THREAD

**Issue by Yatrie** [zueve/neurolab#24]
I am getting following basic error with Python 2.7

    net = nl.net.newff([[-7, 7]],[5, 1])
AttributeError: 'module' object has no attribute 'net'

**Comment by zueve** [comment]
What is nl module, may be you rewrite nl jbject in code? 
How you install neurolab?

**Comment by Yatrie** [comment]
Thanks for reply. I install using PIP. Neurolab present at C:\Python27\Lib\site-packages\neurolab. The code is sample from https://pythonhosted.org/neurolab/ex_newff.html

import neurolab as nl
import numpy as np
import pylab as pl

# Create train samples
x = np.linspace(-7, 7, 20)
y = np.sin(x) * 0.5

size = len(x)

inp = x.reshape(size,1)
tar = y.reshape(size,1)

# Create network with 2 layers and random initialized
net = nl.net.newff([[-7, 7]],[5, 1])

**Comment by zueve** [comment]
I repeat your action in docker container on ubuntu 14.04. All works fine.  I think problem in your local mashine. Remove neurolab dir in your work directory and PYTHONPATH/

**Comment by rohan-m** [comment]
I had the same issue, but including the neurolab dir in the present working dir solves the issue. 
unable to solve keeping the neurolab in PYTHONPATH i.e usr/local/lib/python2.7/dist-packages
