### ISSUE TITLE
How to get a neural network in neurolab to learn more efficiently

### ISSUE THREAD

**Issue by JR768** [zueve/neurolab#40]

**Comment by zueve** [comment]
Hi, it is realy strange. What result your have with another train function

сб, 11 авг. 2018 г., 1:48 chj77 <notifications@github.com>:

**Comment by chj77** [comment]
Thanks for the reply. I've had various results with other training methods, although the best result so far has been with Resilient Backpropagation. Perhaps it was a bit unclear from the example intensity inputs, but there are far fewer intensity centres than background noise. Is the neural network simply converging to 0 to minimise the error? If so, how could I fix this?

**Comment by zueve** [comment]
Maybe your train samples is not clear? For example for same input they have
different target?

сб, 11 авг. 2018 г. в 13:46, chj77 <notifications@github.com>:
