### ISSUE TITLE
Nguyen-Widrow initialization function

### ISSUE THREAD

**Issue by by1e11** [zueve/neurolab#42]
Hello, guys
Thanks for creating the nice neural network library.

Recently I extended the library by adding the LM implementation as in Matlab.
However, when I was training a network, the results are far worse than that in Matlab.

I thought it would be a problem with my LM implementation at the beginning until I tried initialize the parameters in Matlab and load them into neurolab then train with my LM algorithm and that works perfectly.

I then checked the init_nw implementation in neurolab, although I am not an expert of this algorithm, I compared the code with Matlab initnw.m script and I found in the code snippet below there is a mismatch between the two: the last two lines shoud be swapped in Matlab implementation.
* NeuroLab original
```python
# Scaleble to inp_minmax
minmax = layer.inp_minmax.copy()
minmax[np.isneginf(minmax)] = -1
minmax[np.isinf(minmax)] = 1
x = 2. / (minmax[:, 1] - minmax[:, 0])
y = 1. - minmax[:, 1] * x
w = w * x
b = np.dot(w, y) + b
```

Thus, I swapped the last two lines as in Matlab, then it works properly. Could you please your experts have a look at the issue?

* Now
```python
b = np.dot(w, y) + b
w = w * x
```

Thanks

**Comment by zueve** [comment]
Thank you.  I apply your improves
